# 在线程中你怎么处理不可捕捉异常

**异常：**

1.CheckException(非运行时异常)：对于可恢复条件被检查的异常

2.UnCheckException(运行时异常)：已经运行不可恢复的异常。

run()方法不支持throws语句，所以当线程对象的run()方法抛出非运行时异常时，必须捕获并处理他们。当运行时异常从run方法中抛出时，默认行为是在控制台输出堆栈记录并退出程序。

解决方法一般是调用线程的setUncaughtExceptionHandler(UncaughtExceptionHandler x) 在UncaughtExceptionHandler中处理异常。

上代码

1.写个异常，int肯定格式化转换失败抛 java.lang.NumberFormatException:异常

```java
public class ThreadExceptionRun implements Runnable {

    @Override
    public void run() {
        int i = Integer.parseInt("uncaughtException");
        System.out.println(i);
    }



}
```

2.写个异常处理器，实现Thread.UncaughtExceptionHandler重写uncaughtException方法

```java
public class ThreadException implements Thread.UncaughtExceptionHandler {

    @Override
    public void uncaughtException(Thread t, Throwable e) {

        System.out.println("处理异常信息");
    }


}
```

3.测试

```java
public class ThreadExceptionMain {

    public static void main(String[] args) {

        Thread thread  = new Thread(new ThreadExceptionRun());

        thread.setUncaughtExceptionHandler(new ThreadException());
        thread.start();
    }
}
```

如果不设置运行结果uncaughtException的话运行如下：

![img](https://img-blog.csdnimg.cn/20190222110741935.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3NpbmF0XzM2MjY1MjIy,size_16,color_FFFFFF,t_70)

加了异常处理，运行如下： 

![img](https://img-blog.csdnimg.cn/20190222110640432.png)